from datetime import date
from decimal import Decimal
import re

MAX_TITLE_LENGTH = 200

CURRENT_YEAR = date.today().year
MIN_PUBLISHED_YEAR = 1000
MAX_FUTURE_PUBLICATION_YEAR_OFFSET = 1
MAX_FUTURE_PUBLICATION_YEAR = CURRENT_YEAR + MAX_FUTURE_PUBLICATION_YEAR_OFFSET

MIN_PRICE = Decimal("0")
MAX_PRICE = Decimal("10000000")
MAX_PRICE_DECIMAL_PLACES = 2

MIN_STOCK_QUANTITY = 0
MAX_STOCK_QUANTITY = 100_000

ISBN_10_LENGTH = 10
ISBN_13_LENGTH = 13
MAX_ISBN_LENGTH = 20
VALID_ISBN_DIGIT_LENGTHS = {ISBN_10_LENGTH, ISBN_13_LENGTH}
ISBN_ALLOWED_PATTERN = re.compile(r"^[0-9-]+$")
